"""Object registry: name -> ObjectDef (geometry + default material).

OBJECT_MAP is the single source of truth for what each object name spawns. Objects
are either a primitive MPM/rigid box (mesh_path=None) or a scanned mesh (mesh_path
set -> Genesis loads gs.morphs.Mesh). Scanned meshes live in assets/objects/ and are
stored in METERS, so no scale conversion is needed at the call site.

SceneBuilder reads OBJECT_MAP to turn a SceneSpec ObjectEntry (which may override
E/nu/rho/scale/pose) into Genesis morph + material calls.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

from gentle_manip.assets.materials import MATERIALS, Material

_OBJ_DIR = Path(__file__).resolve().parent / "objects"


@dataclass(frozen=True)
class ObjectDef:
    name: str
    material: Material
    object_type: str = "soft"                       # "soft" (MPM) | "rigid"
    size: Tuple[float, float, float] = (0.04, 0.04, 0.04)   # primitive box extents (m)
    default_pos: Tuple[float, float, float] = (0.50, 0.0, 0.03)  # resting pose (m)
    mesh_path: Optional[str] = None                 # reserved; None => primitive box


# The validated baseline matches examples/gs_sim_backend_dev.py: a 4 cm tofu cube
# resting at (0.50, 0, 0.03), within reach and the MPM bounds.
OBJECT_MAP: dict[str, ObjectDef] = {
    # 3 cm tofu block (2026-08-25): the item-1 cube geometry as a SOFT object — the second
    # category for the generalist push. Subdivided cube mesh so shape DR / CMA-ES SDF work.
    "tofu":    ObjectDef("tofu", MATERIALS["tofu"], object_type="soft",
                         size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.0, 0.016),
                         mesh_path=str(_OBJ_DIR / "tofu.obj")),
    "gelatin": ObjectDef("gelatin", MATERIALS["gelatin"]),
    "sponge":  ObjectDef("sponge", MATERIALS["sponge"]),
    # 3 cm cube matching the real red cube the DP3 policy was trained on; rests on
    # the table (half-extent 0.015 -> center z ~0.015 after settling).
    "red_cube": ObjectDef("red_cube", MATERIALS["red_cube"],
                          size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.011, 0.02)),
    # Gripper-width calibration cubes (use as rigid): known sizes spread across x so
    # all four fit in one scene; spawn z = half-extent so they rest on the table.
    "cal_cube_6": ObjectDef("cal_cube_6", MATERIALS["red_cube"], size=(0.06, 0.06, 0.06), default_pos=(0.34, 0.0, 0.035)),
    "cal_cube_5": ObjectDef("cal_cube_5", MATERIALS["red_cube"], size=(0.05, 0.05, 0.05), default_pos=(0.42, 0.0, 0.030)),
    "cal_cube_4": ObjectDef("cal_cube_4", MATERIALS["red_cube"], size=(0.04, 0.04, 0.04), default_pos=(0.50, 0.0, 0.025)),
    "cal_cube_3": ObjectDef("cal_cube_3", MATERIALS["red_cube"], size=(0.03, 0.03, 0.03), default_pos=(0.58, 0.0, 0.020)),
    # Real scanned edible mushroom (assets/objects/mushroom.obj, in meters: ~3.3 x 3.2
    # x 3.5 cm). Soft MPM body; rests on the table (mesh bottom at z=-0.0148, so
    # default_pos z=0.016 puts it just above the surface). size is informational only
    # (ignored for meshes). Material is the soft-end "Config C" (see materials.py).
    "mushroom": ObjectDef("mushroom", MATERIALS["mushroom"], object_type="soft",
                          size=(0.033, 0.032, 0.035), default_pos=(0.47, 0.0, 0.016),
                          mesh_path=str(_OBJ_DIR / "mushroom.obj")),
    # TripoSG-scanned real-mushroom variants (MIT-licensed generator) (item 6): rotated to the same z-up/cap-up
    # convention and uniformly scaled to the nominal mushroom's mean extent (~33 mm); same
    # material/spawn conventions, so they drop into any mushroom task via object name.
    "mushroom1": ObjectDef("mushroom1", MATERIALS["mushroom"], object_type="soft",
                           size=(0.0323, 0.0322, 0.0351), default_pos=(0.47, 0.0, 0.016),
                           mesh_path=str(_OBJ_DIR / "mushroom1.obj")),
    "mushroom2": ObjectDef("mushroom2", MATERIALS["mushroom"], object_type="soft",
                           size=(0.0318, 0.0319, 0.0359), default_pos=(0.47, 0.0, 0.016),
                           mesh_path=str(_OBJ_DIR / "mushroom2.obj")),
    "mushroom3": ObjectDef("mushroom3", MATERIALS["mushroom"], object_type="soft",
                           size=(0.0357, 0.0326, 0.0313), default_pos=(0.47, 0.0, 0.016),
                           mesh_path=str(_OBJ_DIR / "mushroom3.obj")),

    # ── Grasp-benchmark shape set ────────────────────────────────────────────────────────────────
    # Three extra soft objects that bracket the geometry axis the mushroom alone cannot test.
    # Meshes are generated by assets/make_primitive_meshes.py, in METRES, xy-centred with the base
    # at z=0 — so default_pos.z is half-height + ~1 mm clearance (a soft body must SPAWN RESTING;
    # dropping it from height blows up MPM). NOTE object_type here is documentation only: the sim
    # reads `object_type` from the TASK config, not from this field.
    #
    # Cylinder r=2.5cm x h=4cm: smooth and curved with no antipodal faces, and the widest object in
    # the set (5 cm across, vs the gripper's ~7.9 cm usable opening).
    "cylinder": ObjectDef("cylinder", MATERIALS["soft_shape"], object_type="soft",
                          size=(0.05, 0.05, 0.04), default_pos=(0.47, 0.0, 0.021),
                          mesh_path=str(_OBJ_DIR / "cylinder.obj")),
    # Cube 4cm: flat antipodal faces and SHARP edges — the control case for a metric tuned on
    # organic blobs. Must be planned with prepare=False; the FEM path's watertight voxel remesh
    # rounds sharp edges, which would erase exactly what this object is here to test.
    # TRUE 3 cm sharp cube (item 1: the real 3 cm cube probe below the arm). RIGID — the real
    # counterpart is a solid cube; mesh (not Box) so the FEM grasp synthesis can plan on it.
    # spawn z = half-side + 1 mm clearance (centroid-origin mesh).
    "cube3": ObjectDef("cube3", MATERIALS["red_cube"], object_type="rigid",
                       size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.0, 0.016),
                       mesh_path=str(_OBJ_DIR / "cube3.obj")),
    # SOFT twin of cube3 (2026-09-03). ADDITIVE — cube3 stays rigid so every existing dataset and
    # policy is untouched. Same 3 cm mesh, MPM instead of rigid, soft_shape material (E=300 kPa,
    # the stiffest validated MPM preset — "Config C") because it stands in for a real SOLID cube:
    # a softer preset (red_cube, E=30 kPa) would visibly squash under the grasp and diverge from
    # the real object. Used for the 2026-09-03 D435i paired-replay + 200-demo campaign, where the
    # research question is gentleness, so the sim object must be deformable.
    "cube3_soft": ObjectDef("cube3_soft", MATERIALS["soft_shape"], object_type="soft",
                            size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.0, 0.016),
                            mesh_path=str(_OBJ_DIR / "cube3.obj")),
    "cube4": ObjectDef("cube4", MATERIALS["soft_shape"], object_type="soft",
                       size=(0.04, 0.04, 0.04), default_pos=(0.47, 0.0, 0.021),
                       mesh_path=str(_OBJ_DIR / "cube4.obj")),
    # Raspberry ~1.5cm: the small, fragile, bumpy case. NOTE it spans only ~4 cells at the
    # mushroom task's MPM grid density (4 mm cells), so its task config must tighten mpm_bounds and
    # raise mpm_grid_density or the contact is unresolved — see docs/grasp_synthesis_v4_plan.md.
    "cherry_tomato": ObjectDef("cherry_tomato", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.0247, 0.025, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato2.obj")),
    "tomato": ObjectDef("tomato", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0459, 0.0599), default_pos=(0.47, 0.0, 0.0307),
                        mesh_path=str(_OBJ_DIR / "tomato1.obj")),
    "banana_chunk": ObjectDef("banana_chunk", MATERIALS["banana_chunk"], object_type="soft",
                        size=(0.0337, 0.035, 0.0204), default_pos=(0.47, 0.0, 0.011),
                        mesh_path=str(_OBJ_DIR / "banana_chunk.obj")),
    "pasta_bundle": ObjectDef("pasta_bundle", MATERIALS["pasta_bundle"], object_type="soft",
                        size=(0.06, 0.0249, 0.0249), default_pos=(0.47, 0.0, 0.0138),
                        mesh_path=str(_OBJ_DIR / "pasta_bundle.obj")),
    # Photo-derived fruit variants (TripoSG, cluster agent 2026-08-27). Kept = passed the
    # agent's usability gate (topology + photo-silhouette consistency) AND our
    # category-appropriateness check (volume within 0.5-2x the category median, aspect < 1.6,
    # euler 2). Each is uniformly scaled to the category's already-validated nominal extent.
    "cherry_tomato1": ObjectDef("cherry_tomato1", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.025, 0.0241, 0.0245), default_pos=(0.47, 0.0, 0.0132),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato1.obj")),
    "cherry_tomato2": ObjectDef("cherry_tomato2", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.0247, 0.025, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato2.obj")),
    "cherry_tomato3": ObjectDef("cherry_tomato3", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.025, 0.0167, 0.0194), default_pos=(0.47, 0.0, 0.0107),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato3.obj")),
    "cherry_tomato5": ObjectDef("cherry_tomato5", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.0198, 0.025, 0.0198), default_pos=(0.47, 0.0, 0.0113),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato5.obj")),
    # raspberry is PARKED (2026-09-06): shatters on spawn in MPM across every tried fix — spawn
    # height, cherry-level material (+substeps 760: NaN), and smoothed neck-free meshes
    # (raspberryN_smooth.obj, kept beside the originals) all failed; full trail in DEVLOG.
    "raspberry1": ObjectDef("raspberry1", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0154, 0.0153, 0.0154), default_pos=(0.47, 0.0, 0.0087),
                        mesh_path=str(_OBJ_DIR / "raspberry1.obj")),
    "raspberry2": ObjectDef("raspberry2", MATERIALS["raspberry"], object_type="soft",
                        size=(0.014, 0.0154, 0.0137), default_pos=(0.47, 0.0, 0.0079),
                        mesh_path=str(_OBJ_DIR / "raspberry2.obj")),
    "raspberry3": ObjectDef("raspberry3", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0154, 0.012, 0.0133), default_pos=(0.47, 0.0, 0.0078),
                        mesh_path=str(_OBJ_DIR / "raspberry3.obj")),
    "raspberry4": ObjectDef("raspberry4", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0154, 0.0117, 0.0113), default_pos=(0.47, 0.0, 0.0067),
                        mesh_path=str(_OBJ_DIR / "raspberry4.obj")),
    "raspberry5": ObjectDef("raspberry5", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0146, 0.0154, 0.0149), default_pos=(0.47, 0.0, 0.0083),
                        mesh_path=str(_OBJ_DIR / "raspberry5.obj")),
    "tomato1": ObjectDef("tomato1", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0459, 0.0599), default_pos=(0.47, 0.0, 0.0307),
                        mesh_path=str(_OBJ_DIR / "tomato1.obj")),
    "tomato3": ObjectDef("tomato3", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0527, 0.0599), default_pos=(0.47, 0.0, 0.0308),
                        mesh_path=str(_OBJ_DIR / "tomato3.obj")),
    "tomato4": ObjectDef("tomato4", MATERIALS["tomato"], object_type="soft",
                        size=(0.0531, 0.06, 0.0516), default_pos=(0.47, 0.0, 0.0268),
                        mesh_path=str(_OBJ_DIR / "tomato4.obj")),
    "tomato5": ObjectDef("tomato5", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0537, 0.059), default_pos=(0.47, 0.0, 0.0303),
                        mesh_path=str(_OBJ_DIR / "tomato5.obj")),
    # Primitive diversity objects (2026-08-30, user request) — ALL tofu material. Shape-class
    # probes for the FROZEN v4.1 synthesis: cylinder/sphere/lamp user-specified; cuboid/
    # ellipsoid/torus proposed (flat-face + smooth anisotropy + topology). v4.1 parameters are
    # NOT to be modified regardless of how these perform (paper freeze, deadline 2026-09-15).
    "prim_cylinder": ObjectDef("prim_cylinder", MATERIALS["tofu"], object_type="soft",
                        size=(0.04, 0.04, 0.05), default_pos=(0.47, 0.0, 0.026),
                        mesh_path=str(_OBJ_DIR / "prim_cylinder.obj")),
    "prim_sphere": ObjectDef("prim_sphere", MATERIALS["tofu"], object_type="soft",
                        size=(0.04, 0.04, 0.04), default_pos=(0.47, 0.0, 0.021),
                        mesh_path=str(_OBJ_DIR / "prim_sphere.obj")),
    "prim_lamp": ObjectDef("prim_lamp", MATERIALS["tofu"], object_type="soft",
                        size=(0.03, 0.03, 0.052), default_pos=(0.47, 0.0, 0.037),
                        mesh_path=str(_OBJ_DIR / "prim_lamp.obj")),
    "prim_cuboid": ObjectDef("prim_cuboid", MATERIALS["tofu"], object_type="soft",
                        size=(0.04, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_cuboid.obj")),
    "prim_ellipsoid": ObjectDef("prim_ellipsoid", MATERIALS["tofu"], object_type="soft",
                        size=(0.05, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_ellipsoid.obj")),
    "prim_torus": ObjectDef("prim_torus", MATERIALS["tofu"], object_type="soft",
                        size=(0.042, 0.042, 0.014), default_pos=(0.47, 0.0, 0.008),
                        mesh_path=str(_OBJ_DIR / "prim_torus.obj")),
    # *_mush VARIANTS (2026-08-31): the same six primitive meshes with MUSHROOM material,
    # ADDED as separate entries per user instruction (never override existing entries — the
    # tofu-material prim_* set above stays intact for the material A/B and to avoid merge
    # conflicts with the cluster). Force-budget prediction: curved shapes recover to ~75-90%.
    "prim_cylinder_mush": ObjectDef("prim_cylinder_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.04, 0.04, 0.05), default_pos=(0.47, 0.0, 0.026),
                        mesh_path=str(_OBJ_DIR / "prim_cylinder.obj")),
    "prim_sphere_mush": ObjectDef("prim_sphere_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.04, 0.04, 0.04), default_pos=(0.47, 0.0, 0.021),
                        mesh_path=str(_OBJ_DIR / "prim_sphere.obj")),
    "prim_lamp_mush": ObjectDef("prim_lamp_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.03, 0.03, 0.052), default_pos=(0.47, 0.0, 0.037),
                        mesh_path=str(_OBJ_DIR / "prim_lamp.obj")),
    "prim_cuboid_mush": ObjectDef("prim_cuboid_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.04, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_cuboid.obj")),
    "prim_ellipsoid_mush": ObjectDef("prim_ellipsoid_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.05, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_ellipsoid.obj")),
    "prim_torus_mush": ObjectDef("prim_torus_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.042, 0.042, 0.014), default_pos=(0.47, 0.0, 0.008),
                        mesh_path=str(_OBJ_DIR / "prim_torus.obj")),
    # 2026-09-07 (local collection, user): three more primitives, 3 cm nominal extent, mushroom material.
    "prim_capsule_mush": ObjectDef("prim_capsule_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.03, 0.018, 0.018), default_pos=(0.47, 0.0, 0.0100),
                        mesh_path=str(_OBJ_DIR / "prim_capsule.obj")),
    "prim_hexprism_mush": ObjectDef("prim_hexprism_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.03, 0.026, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_hexprism.obj")),

    # ── 2026-09-09 ADDITIVE: 84 canonical cuboids (sides from {20,25,30,35,40,45,50} mm,
    # x<=y<=z so no entry is a rotation of another) + 3 drink cans + 1 donut. All use the
    # mushroom material and the prim_*_mush DR ranges; size/default_pos/spawn are per-mesh.
    "box_020x020x020_mush": ObjectDef("box_020x020x020_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0200, 0.0200), default_pos=(0.47, 0.0, 0.0110),
                        mesh_path=str(_OBJ_DIR / "box_020x020x020_mush.obj")),
    "box_020x020x025_mush": ObjectDef("box_020x020x025_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0200, 0.0250), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "box_020x020x025_mush.obj")),
    "box_020x020x030_mush": ObjectDef("box_020x020x030_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0200, 0.0300), default_pos=(0.47, 0.0, 0.0160),
                        mesh_path=str(_OBJ_DIR / "box_020x020x030_mush.obj")),
    "box_020x020x035_mush": ObjectDef("box_020x020x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0200, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_020x020x035_mush.obj")),
    "box_020x020x040_mush": ObjectDef("box_020x020x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0200, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_020x020x040_mush.obj")),
    "box_020x020x045_mush": ObjectDef("box_020x020x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0200, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_020x020x045_mush.obj")),
    "box_020x020x050_mush": ObjectDef("box_020x020x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0200, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_020x020x050_mush.obj")),
    "box_020x025x025_mush": ObjectDef("box_020x025x025_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0250, 0.0250), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "box_020x025x025_mush.obj")),
    "box_020x025x030_mush": ObjectDef("box_020x025x030_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0250, 0.0300), default_pos=(0.47, 0.0, 0.0160),
                        mesh_path=str(_OBJ_DIR / "box_020x025x030_mush.obj")),
    "box_020x025x035_mush": ObjectDef("box_020x025x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0250, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_020x025x035_mush.obj")),
    "box_020x025x040_mush": ObjectDef("box_020x025x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0250, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_020x025x040_mush.obj")),
    "box_020x025x045_mush": ObjectDef("box_020x025x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0250, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_020x025x045_mush.obj")),
    "box_020x025x050_mush": ObjectDef("box_020x025x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0250, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_020x025x050_mush.obj")),
    "box_020x030x030_mush": ObjectDef("box_020x030x030_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0300, 0.0300), default_pos=(0.47, 0.0, 0.0160),
                        mesh_path=str(_OBJ_DIR / "box_020x030x030_mush.obj")),
    "box_020x030x035_mush": ObjectDef("box_020x030x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0300, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_020x030x035_mush.obj")),
    "box_020x030x040_mush": ObjectDef("box_020x030x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0300, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_020x030x040_mush.obj")),
    "box_020x030x045_mush": ObjectDef("box_020x030x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0300, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_020x030x045_mush.obj")),
    "box_020x030x050_mush": ObjectDef("box_020x030x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0300, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_020x030x050_mush.obj")),
    "box_020x035x035_mush": ObjectDef("box_020x035x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0350, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_020x035x035_mush.obj")),
    "box_020x035x040_mush": ObjectDef("box_020x035x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0350, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_020x035x040_mush.obj")),
    "box_020x035x045_mush": ObjectDef("box_020x035x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0350, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_020x035x045_mush.obj")),
    "box_020x035x050_mush": ObjectDef("box_020x035x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0350, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_020x035x050_mush.obj")),
    "box_020x040x040_mush": ObjectDef("box_020x040x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0400, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_020x040x040_mush.obj")),
    "box_020x040x045_mush": ObjectDef("box_020x040x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0400, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_020x040x045_mush.obj")),
    "box_020x040x050_mush": ObjectDef("box_020x040x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0400, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_020x040x050_mush.obj")),
    "box_020x045x045_mush": ObjectDef("box_020x045x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0450, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_020x045x045_mush.obj")),
    "box_020x045x050_mush": ObjectDef("box_020x045x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0450, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_020x045x050_mush.obj")),
    "box_020x050x050_mush": ObjectDef("box_020x050x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0200, 0.0500, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_020x050x050_mush.obj")),
    "box_025x025x025_mush": ObjectDef("box_025x025x025_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0250, 0.0250), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "box_025x025x025_mush.obj")),
    "box_025x025x030_mush": ObjectDef("box_025x025x030_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0250, 0.0300), default_pos=(0.47, 0.0, 0.0160),
                        mesh_path=str(_OBJ_DIR / "box_025x025x030_mush.obj")),
    "box_025x025x035_mush": ObjectDef("box_025x025x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0250, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_025x025x035_mush.obj")),
    "box_025x025x040_mush": ObjectDef("box_025x025x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0250, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_025x025x040_mush.obj")),
    "box_025x025x045_mush": ObjectDef("box_025x025x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0250, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_025x025x045_mush.obj")),
    "box_025x025x050_mush": ObjectDef("box_025x025x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0250, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_025x025x050_mush.obj")),
    "box_025x030x030_mush": ObjectDef("box_025x030x030_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0300, 0.0300), default_pos=(0.47, 0.0, 0.0160),
                        mesh_path=str(_OBJ_DIR / "box_025x030x030_mush.obj")),
    "box_025x030x035_mush": ObjectDef("box_025x030x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0300, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_025x030x035_mush.obj")),
    "box_025x030x040_mush": ObjectDef("box_025x030x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0300, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_025x030x040_mush.obj")),
    "box_025x030x045_mush": ObjectDef("box_025x030x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0300, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_025x030x045_mush.obj")),
    "box_025x030x050_mush": ObjectDef("box_025x030x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0300, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_025x030x050_mush.obj")),
    "box_025x035x035_mush": ObjectDef("box_025x035x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0350, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_025x035x035_mush.obj")),
    "box_025x035x040_mush": ObjectDef("box_025x035x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0350, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_025x035x040_mush.obj")),
    "box_025x035x045_mush": ObjectDef("box_025x035x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0350, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_025x035x045_mush.obj")),
    "box_025x035x050_mush": ObjectDef("box_025x035x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0350, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_025x035x050_mush.obj")),
    "box_025x040x040_mush": ObjectDef("box_025x040x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0400, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_025x040x040_mush.obj")),
    "box_025x040x045_mush": ObjectDef("box_025x040x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0400, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_025x040x045_mush.obj")),
    "box_025x040x050_mush": ObjectDef("box_025x040x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0400, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_025x040x050_mush.obj")),
    "box_025x045x045_mush": ObjectDef("box_025x045x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0450, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_025x045x045_mush.obj")),
    "box_025x045x050_mush": ObjectDef("box_025x045x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0450, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_025x045x050_mush.obj")),
    "box_025x050x050_mush": ObjectDef("box_025x050x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0250, 0.0500, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_025x050x050_mush.obj")),
    "box_030x030x030_mush": ObjectDef("box_030x030x030_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0300, 0.0300), default_pos=(0.47, 0.0, 0.0160),
                        mesh_path=str(_OBJ_DIR / "box_030x030x030_mush.obj")),
    "box_030x030x035_mush": ObjectDef("box_030x030x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0300, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_030x030x035_mush.obj")),
    "box_030x030x040_mush": ObjectDef("box_030x030x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0300, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_030x030x040_mush.obj")),
    "box_030x030x045_mush": ObjectDef("box_030x030x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0300, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_030x030x045_mush.obj")),
    "box_030x030x050_mush": ObjectDef("box_030x030x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0300, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_030x030x050_mush.obj")),
    "box_030x035x035_mush": ObjectDef("box_030x035x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0350, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_030x035x035_mush.obj")),
    "box_030x035x040_mush": ObjectDef("box_030x035x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0350, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_030x035x040_mush.obj")),
    "box_030x035x045_mush": ObjectDef("box_030x035x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0350, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_030x035x045_mush.obj")),
    "box_030x035x050_mush": ObjectDef("box_030x035x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0350, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_030x035x050_mush.obj")),
    "box_030x040x040_mush": ObjectDef("box_030x040x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0400, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_030x040x040_mush.obj")),
    "box_030x040x045_mush": ObjectDef("box_030x040x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0400, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_030x040x045_mush.obj")),
    "box_030x040x050_mush": ObjectDef("box_030x040x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0400, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_030x040x050_mush.obj")),
    "box_030x045x045_mush": ObjectDef("box_030x045x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0450, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_030x045x045_mush.obj")),
    "box_030x045x050_mush": ObjectDef("box_030x045x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0450, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_030x045x050_mush.obj")),
    "box_030x050x050_mush": ObjectDef("box_030x050x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0300, 0.0500, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_030x050x050_mush.obj")),
    "box_035x035x035_mush": ObjectDef("box_035x035x035_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0350, 0.0350), default_pos=(0.47, 0.0, 0.0185),
                        mesh_path=str(_OBJ_DIR / "box_035x035x035_mush.obj")),
    "box_035x035x040_mush": ObjectDef("box_035x035x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0350, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_035x035x040_mush.obj")),
    "box_035x035x045_mush": ObjectDef("box_035x035x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0350, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_035x035x045_mush.obj")),
    "box_035x035x050_mush": ObjectDef("box_035x035x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0350, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_035x035x050_mush.obj")),
    "box_035x040x040_mush": ObjectDef("box_035x040x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0400, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_035x040x040_mush.obj")),
    "box_035x040x045_mush": ObjectDef("box_035x040x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0400, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_035x040x045_mush.obj")),
    "box_035x040x050_mush": ObjectDef("box_035x040x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0400, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_035x040x050_mush.obj")),
    "box_035x045x045_mush": ObjectDef("box_035x045x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0450, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_035x045x045_mush.obj")),
    "box_035x045x050_mush": ObjectDef("box_035x045x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0450, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_035x045x050_mush.obj")),
    "box_035x050x050_mush": ObjectDef("box_035x050x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0350, 0.0500, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_035x050x050_mush.obj")),
    "box_040x040x040_mush": ObjectDef("box_040x040x040_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0400, 0.0400, 0.0400), default_pos=(0.47, 0.0, 0.0210),
                        mesh_path=str(_OBJ_DIR / "box_040x040x040_mush.obj")),
    "box_040x040x045_mush": ObjectDef("box_040x040x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0400, 0.0400, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_040x040x045_mush.obj")),
    "box_040x040x050_mush": ObjectDef("box_040x040x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0400, 0.0400, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_040x040x050_mush.obj")),
    "box_040x045x045_mush": ObjectDef("box_040x045x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0400, 0.0450, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_040x045x045_mush.obj")),
    "box_040x045x050_mush": ObjectDef("box_040x045x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0400, 0.0450, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_040x045x050_mush.obj")),
    "box_040x050x050_mush": ObjectDef("box_040x050x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0400, 0.0500, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_040x050x050_mush.obj")),
    "box_045x045x045_mush": ObjectDef("box_045x045x045_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0450, 0.0450, 0.0450), default_pos=(0.47, 0.0, 0.0235),
                        mesh_path=str(_OBJ_DIR / "box_045x045x045_mush.obj")),
    "box_045x045x050_mush": ObjectDef("box_045x045x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0450, 0.0450, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_045x045x050_mush.obj")),
    "box_045x050x050_mush": ObjectDef("box_045x050x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0450, 0.0500, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_045x050x050_mush.obj")),
    "box_050x050x050_mush": ObjectDef("box_050x050x050_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0500, 0.0500, 0.0500), default_pos=(0.47, 0.0, 0.0260),
                        mesh_path=str(_OBJ_DIR / "box_050x050x050_mush.obj")),

    # ── 2026-09-09 ADDITIVE: paprika (single mesh) and the pepper CATEGORY (pepper1 from
    # Pepper.obj, pepper2 from Sweet_long_pepper_SF.obj) — the DR draws a variant per scene
    # via object_mesh_pool, the cherry_tomato pattern. Mushroom material.
    "paprika": ObjectDef("paprika", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0600, 0.0544, 0.0568), default_pos=(0.47, 0.0, 0.0294),
                        mesh_path=str(_OBJ_DIR / "paprika.obj")),
    "pepper1": ObjectDef("pepper1", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0422, 0.0156, 0.0144), default_pos=(0.47, 0.0, 0.0082),
                        mesh_path=str(_OBJ_DIR / "pepper1.obj")),
    "pepper2": ObjectDef("pepper2", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0630, 0.0127, 0.0173), default_pos=(0.47, 0.0, 0.0097),
                        mesh_path=str(_OBJ_DIR / "pepper2.obj")),
    # Standing disc, d 70 x h 25 mm (2026-09-09), yaw-only DR like the other new objects.
    "cyl_d070h025_mush": ObjectDef("cyl_d070h025_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0700, 0.0700, 0.0250), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "cyl_d070h025_mush.obj")),
    # banana_mush (2026-09-09): the existing banana.obj with the mushroom material and the
    # prim_*_mush recipe; the 2026-08-26 `banana` entry above is left as it is.
    "banana_mush": ObjectDef("banana_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0707, 0.0950, 0.0186), default_pos=(0.47, 0.0, 0.0103),
                        mesh_path=str(_OBJ_DIR / "banana.obj")),
    "pepper": ObjectDef("pepper", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0422, 0.0156, 0.0144), default_pos=(0.47, 0.0, 0.0082),
                        mesh_path=str(_OBJ_DIR / "pepper1.obj")),
    # Lying rod, 15 mm dia x 100 mm, long axis +X like can_lying_mush (user, 2026-09-10). prim_*_mush
    # material; 17.6 g at rho 1000. Thin enough that the gripper closes on the DIAMETER, long enough
    # (100 mm > LARGE_EXTENT_M) that the synthesizer gets the full yaw box.
    "rod_d015l100_mush": ObjectDef("rod_d015l100_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.1000, 0.0150, 0.0150), default_pos=(0.47, 0.0, 0.0085),
                        mesh_path=str(_OBJ_DIR / "rod_d015l100_mush.obj")),
    "can_lying_mush": ObjectDef("can_lying_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.1500, 0.0650, 0.0650), default_pos=(0.47, 0.0, 0.0335),
                        mesh_path=str(_OBJ_DIR / "can_lying_mush.obj")),
    "beer_can_lying_mush": ObjectDef("beer_can_lying_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0850, 0.0650, 0.0650), default_pos=(0.47, 0.0, 0.0335),
                        mesh_path=str(_OBJ_DIR / "beer_can_lying_mush.obj")),
    "beer_can_standing_mush": ObjectDef("beer_can_standing_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0650, 0.0650, 0.0850), default_pos=(0.47, 0.0, 0.0435),
                        mesh_path=str(_OBJ_DIR / "beer_can_standing_mush.obj")),
    # Donut scaled 2.5x from the original 8 cm ring (user, 2026-09-10): outer RADIUS 10 cm, so
    # 20 cm across — past the gripper's 7.9 cm opening, and the planner CANNOT grasp the disc as a
    # whole. The only feasible grasp is the ring itself (3.75 cm tube, either axis). default_pos x is
    # the DOMAIN centre 0.385, not the usual 0.47 — at 20 cm wide it does not fit otherwise, and the
    # BUILD reads this, not the DR object_nominal_xy. This is the
    # forced-ring-grasp probe; the 8 cm version is recoverable by scaling the mesh 1/2.5.
    "donut_mush": ObjectDef("donut_mush", MATERIALS["donut"], object_type="soft",
                        size=(0.2000, 0.2000, 0.0375), default_pos=(0.385, 0.0, 0.0198),
                        mesh_path=str(_OBJ_DIR / "donut_mush.obj")),
    # The 10 cm sibling of donut_mush (user, 2026-09-10): same mesh, same proportions, 0.5x. 50 g at
    # rho 709, and small enough for the NORMAL spawn (0.47). The ring grasp is forced at EVERY DR
    # draw (smallest is 9.03 cm across vs the 7.9 cm opening) but with less headroom than the 20 cm
    # donut, so this is the marginal-size companion to it.
    "donut_mush_small": ObjectDef("donut_mush_small", MATERIALS["donut_small"], object_type="soft",
                        size=(0.1000, 0.1000, 0.0188), default_pos=(0.47, 0.0, 0.0104),
                        mesh_path=str(_OBJ_DIR / "donut_mush_small.obj")),
    "prim_frustum_mush": ObjectDef("prim_frustum_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.03, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_frustum.obj")),
    "raspberry": ObjectDef("raspberry", MATERIALS["raspberry"], object_type="soft",
                        size=(0.014, 0.0154, 0.0137), default_pos=(0.47, 0.0, 0.0079),
                        mesh_path=str(_OBJ_DIR / "raspberry2.obj")),
    # Banana ~9.5 cm (photo-reconstructed, stem + its flat cut face removed; user-set nominal
    # extent). The mesh is a strong crescent, so the bbox is nearly square in plane
    # (9.5 x 9.2 cm) and 3.24 cm thick — the thickness is what the gripper closes on. At this
    # size it is ~70 g, needing only ~0.5 N of grip; the earlier 17 cm cut was 398 g (~2.8 N)
    # and its 20 cm CMA search box made the planner miss the thin feasible band entirely.
    "banana": ObjectDef("banana", MATERIALS["banana"], object_type="soft",
                        size=(0.0707, 0.095, 0.0186), default_pos=(0.47, 0.0, 0.0104),
                        mesh_path=str(_OBJ_DIR / "banana.obj")),
    # Strawberry ~4 cm (photo-reconstructed, calyx/leaves removed and the body made watertight
    # by a voxel remesh with morphological opening). Squat: 4.0 x 3.8 x 3.25 cm (tip->crown is
    # the SHORT axis, z), so an exact "4 cm long x 3 cm wide" is not reachable without
    # distorting it — uniformly scaled to a 4 cm longest extent instead.
    "strawberry": ObjectDef("strawberry", MATERIALS["strawberry"], object_type="soft",
                            size=(0.040, 0.038, 0.0325), default_pos=(0.47, 0.0, 0.0204),
                            mesh_path=str(_OBJ_DIR / "strawberry.obj")),
}


# ── Extruded letters A-Z (2026-09-05): ~50 mm tall, 25 mm thick (thickened 2026-09-05), lying FLAT (thin axis = z),
# MUSHROOM material (tofu's 50 kPa gave marginal grip on strokes) — complex-geometry test objects. Meshes are metres, centroid at the origin. Additive.
OBJECT_MAP.update({
    "letter_a": ObjectDef("letter_a", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0486, 0.0500, 0.0058), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_a.obj")),
    "letter_b": ObjectDef("letter_b", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0343, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_b.obj")),
    "letter_c": ObjectDef("letter_c", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0439, 0.0500, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_c.obj")),
    "letter_d": ObjectDef("letter_d", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0460, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_d.obj")),
    "letter_e": ObjectDef("letter_e", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0290, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_e.obj")),
    "letter_f": ObjectDef("letter_f", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0267, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_f.obj")),
    "letter_g": ObjectDef("letter_g", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0445, 0.0500, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_g.obj")),
    "letter_h": ObjectDef("letter_h", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0424, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_h.obj")),
    "letter_i": ObjectDef("letter_i", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0072, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_i.obj")),
    "letter_j": ObjectDef("letter_j", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0129, 0.0500, 0.0044), default_pos=(0.47, 0.0, 0.0032),
                        mesh_path=str(_OBJ_DIR / "letter_j.obj")),
    "letter_k": ObjectDef("letter_k", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0425, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_k.obj")),
    "letter_l": ObjectDef("letter_l", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0298, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_l.obj")),
    "letter_m": ObjectDef("letter_m", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0466, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_m.obj")),
    "letter_n": ObjectDef("letter_n", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0463, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_n.obj")),
    "letter_o": ObjectDef("letter_o", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0500, 0.0477, 0.0055), default_pos=(0.47, 0.0, 0.0037),
                        mesh_path=str(_OBJ_DIR / "letter_o.obj")),
    "letter_p": ObjectDef("letter_p", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0315, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_p.obj")),
    "letter_q": ObjectDef("letter_q", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0443, 0.0500, 0.0048), default_pos=(0.47, 0.0, 0.0034),
                        mesh_path=str(_OBJ_DIR / "letter_q.obj")),
    "letter_r": ObjectDef("letter_r", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0386, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_r.obj")),
    "letter_s": ObjectDef("letter_s", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0276, 0.0500, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_s.obj")),
    "letter_t": ObjectDef("letter_t", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0418, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_t.obj")),
    "letter_u": ObjectDef("letter_u", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0425, 0.0500, 0.0058), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_u.obj")),
    "letter_v": ObjectDef("letter_v", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0439, 0.0500, 0.0058), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_v.obj")),
    "letter_w": ObjectDef("letter_w", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0500, 0.0330, 0.0038), default_pos=(0.47, 0.0, 0.0029),
                        mesh_path=str(_OBJ_DIR / "letter_w.obj")),
    "letter_x": ObjectDef("letter_x", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0500, 0.0484, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_x.obj")),
    "letter_y": ObjectDef("letter_y", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0443, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_y.obj")),
    "letter_z": ObjectDef("letter_z", MATERIALS["mushroom"], object_type="soft",
                        size=(0.0451, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_z.obj")),
})

# ── basic-shapes batch + torus (2026-09-07): 18 primitives from the basic_shapes GLB
# (repaired watertight, rescaled to U(2.5,4.5)cm seed 7; GLB node names kept — some are
# misleading: bs_cube is an octahedron) + prim_torus_mush (prim_torus z-thickened to 25mm).
# Mushroom material, prim_sphere_mush-style DR. ADDITIVE per docs/adding_new_objects.md. ──
OBJECT_MAP.update({
    "bs_cube": ObjectDef("bs_cube", MATERIALS["mushroom"], object_type="soft",
                    size=(0.03738, 0.0375, 0.03728), default_pos=(0.47, 0.0, 0.0196),
                    mesh_path=str(_OBJ_DIR / "bs_cube.obj")),
    "bs_cube2": ObjectDef("bs_cube2", MATERIALS["mushroom"], object_type="soft",
                    size=(0.03585, 0.04294, 0.04287), default_pos=(0.47, 0.0, 0.0224),
                    mesh_path=str(_OBJ_DIR / "bs_cube2.obj")),
    "bs_cube3": ObjectDef("bs_cube3", MATERIALS["mushroom"], object_type="soft",
                    size=(0.04049, 0.04051, 0.04051), default_pos=(0.47, 0.0, 0.0213),
                    mesh_path=str(_OBJ_DIR / "bs_cube3.obj")),
    "bs_cube4": ObjectDef("bs_cube4", MATERIALS["mushroom"], object_type="soft",
                    size=(0.02942, 0.02138, 0.0295), default_pos=(0.47, 0.0, 0.0158),
                    mesh_path=str(_OBJ_DIR / "bs_cube4.obj")),
    "bs_cube5": ObjectDef("bs_cube5", MATERIALS["mushroom"], object_type="soft",
                    size=(0.01882, 0.031, 0.02404), default_pos=(0.47, 0.0, 0.013),
                    mesh_path=str(_OBJ_DIR / "bs_cube5.obj")),
    "bs_cylinder": ObjectDef("bs_cylinder", MATERIALS["mushroom"], object_type="soft",
                    size=(0.04055, 0.04247, 0.03494), default_pos=(0.47, 0.0, 0.0185),
                    mesh_path=str(_OBJ_DIR / "bs_cylinder.obj")),
    "bs_cylinder2": ObjectDef("bs_cylinder2", MATERIALS["mushroom"], object_type="soft",
                    size=(0.01184, 0.02511, 0.01309), default_pos=(0.47, 0.0, 0.0075),
                    mesh_path=str(_OBJ_DIR / "bs_cylinder2.obj")),
    "bs_cylinder3": ObjectDef("bs_cylinder3", MATERIALS["mushroom"], object_type="soft",
                    size=(0.01881, 0.04142, 0.02143), default_pos=(0.47, 0.0, 0.0117),
                    mesh_path=str(_OBJ_DIR / "bs_cylinder3.obj")),
    "bs_decagon_pyramid": ObjectDef("bs_decagon_pyramid", MATERIALS["mushroom"], object_type="soft",
                    size=(0.02177, 0.04094, 0.02389), default_pos=(0.47, 0.0, 0.0129),
                    mesh_path=str(_OBJ_DIR / "bs_decagon_pyramid.obj")),
    "bs_dodecagon_sphere": ObjectDef("bs_dodecagon_sphere", MATERIALS["mushroom"], object_type="soft",
                    size=(0.03436, 0.03419, 0.03434), default_pos=(0.47, 0.0, 0.0182),
                    mesh_path=str(_OBJ_DIR / "bs_dodecagon_sphere.obj")),
    "bs_hexagonal_pyramid": ObjectDef("bs_hexagonal_pyramid", MATERIALS["mushroom"], object_type="soft",
                    size=(0.02457, 0.03106, 0.02097), default_pos=(0.47, 0.0, 0.0115),
                    mesh_path=str(_OBJ_DIR / "bs_hexagonal_pyramid.obj")),
    "bs_icosahedron": ObjectDef("bs_icosahedron", MATERIALS["mushroom"], object_type="soft",
                    size=(0.03057, 0.03026, 0.02997), default_pos=(0.47, 0.0, 0.016),
                    mesh_path=str(_OBJ_DIR / "bs_icosahedron.obj")),
    "bs_icosphere": ObjectDef("bs_icosphere", MATERIALS["mushroom"], object_type="soft",
                    size=(0.02866, 0.0301, 0.03009), default_pos=(0.47, 0.0, 0.016),
                    mesh_path=str(_OBJ_DIR / "bs_icosphere.obj")),
    "bs_pentagon": ObjectDef("bs_pentagon", MATERIALS["mushroom"], object_type="soft",
                    size=(0.0339, 0.02747, 0.03239), default_pos=(0.47, 0.0, 0.0172),
                    mesh_path=str(_OBJ_DIR / "bs_pentagon.obj")),
    "bs_pyramid": ObjectDef("bs_pyramid", MATERIALS["mushroom"], object_type="soft",
                    size=(0.03509, 0.02733, 0.03503), default_pos=(0.47, 0.0, 0.0185),
                    mesh_path=str(_OBJ_DIR / "bs_pyramid.obj")),
    "bs_quadrangular_pyramid": ObjectDef("bs_quadrangular_pyramid", MATERIALS["mushroom"], object_type="soft",
                    size=(0.03015, 0.03607, 0.03535), default_pos=(0.47, 0.0, 0.0187),
                    mesh_path=str(_OBJ_DIR / "bs_quadrangular_pyramid.obj")),
    "bs_sphere": ObjectDef("bs_sphere", MATERIALS["mushroom"], object_type="soft",
                    size=(0.04479, 0.04464, 0.04491), default_pos=(0.47, 0.0, 0.0235),
                    mesh_path=str(_OBJ_DIR / "bs_sphere.obj")),
    "bs_star": ObjectDef("bs_star", MATERIALS["mushroom"], object_type="soft",
                    size=(0.04085, 0.03905, 0.03885), default_pos=(0.47, 0.0, 0.0204),
                    mesh_path=str(_OBJ_DIR / "bs_star.obj")),
    "prim_torus_mush": ObjectDef("prim_torus_mush", MATERIALS["mushroom"], object_type="soft",
                    size=(0.042, 0.042, 0.025), default_pos=(0.47, 0.0, 0.0135),
                    mesh_path=str(_OBJ_DIR / "prim_torus_mush.obj")),
})


# # hose: Objaverse-LVIS hose (unknown bucket, uid 3490102dac814280b983f9ac95da20c9), object-expansion batch
OBJECT_MAP.update({
    "hose": ObjectDef("hose", MATERIALS["objexp_hose"], object_type="soft",
                    size=(0.07488, 0.03298, 0.11472), default_pos=(0.47, 0.0, 0.0684),
                    mesh_path=str(_OBJ_DIR / "hose.obj")),
})

# # lemonade: Objaverse-LVIS lemonade (unknown bucket, uid b56da3df5deb4a08b3f9519be1971085), object-expansion batch
OBJECT_MAP.update({
    "lemonade": ObjectDef("lemonade", MATERIALS["objexp_lemonade"], object_type="soft",
                    size=(0.05892, 0.05899, 0.10149), default_pos=(0.47, 0.0, 0.0514),
                    mesh_path=str(_OBJ_DIR / "lemonade.obj")),
})

# # license_plate: Objaverse-LVIS license_plate (unknown bucket, uid becbef04dbf04d58b32574c79b11e30c), object-expansion batch
OBJECT_MAP.update({
    "license_plate": ObjectDef("license_plate", MATERIALS["objexp_license_plate"], object_type="soft",
                    size=(0.05428, 0.11697, 0.03657), default_pos=(0.47, 0.0, 0.0184),
                    mesh_path=str(_OBJ_DIR / "license_plate.obj")),
})

# # martini: Objaverse-LVIS martini (unknown bucket, uid 0c18856042ec43458ac04a4a0ed9311e), object-expansion batch
OBJECT_MAP.update({
    "martini": ObjectDef("martini", MATERIALS["objexp_martini"], object_type="soft",
                    size=(0.04837, 0.04842, 0.04642), default_pos=(0.47, 0.0, 0.0316),
                    mesh_path=str(_OBJ_DIR / "martini.obj")),
})

# # napkin: Objaverse-LVIS napkin (unknown bucket, uid 1dd090467398430191a9b5dfd2d0a9ee), object-expansion batch
OBJECT_MAP.update({
    "napkin": ObjectDef("napkin", MATERIALS["objexp_napkin"], object_type="soft",
                    size=(0.10709, 0.05223, 0.04626), default_pos=(0.47, 0.0, 0.0254),
                    mesh_path=str(_OBJ_DIR / "napkin.obj")),
})

# # oil_lamp: Objaverse-LVIS oil_lamp (unknown bucket, uid 6d5c188ddfe143db90961503933f17d9), object-expansion batch
OBJECT_MAP.update({
    "oil_lamp": ObjectDef("oil_lamp", MATERIALS["objexp_oil_lamp"], object_type="soft",
                    size=(0.04852, 0.04933, 0.08659), default_pos=(0.47, 0.0, 0.0403),
                    mesh_path=str(_OBJ_DIR / "oil_lamp.obj")),
})

# # painting: Objaverse-LVIS painting (unknown bucket, uid 460a5ca01e0e409cafaa5611e564f04b), object-expansion batch
OBJECT_MAP.update({
    "painting": ObjectDef("painting", MATERIALS["soft_shape"], object_type="soft",
                    size=(1.26404, 0.07972, 1.66542), default_pos=(0.47, 0.0, 0.8011),
                    mesh_path=str(_OBJ_DIR / "painting.obj")),
})

# # pan: Objaverse-LVIS pan_(for_cooking) (unknown bucket, uid d501c3ff798945cebee84d7944edb19d), object-expansion batch
OBJECT_MAP.update({
    "pan": ObjectDef("pan", MATERIALS["objexp_pan"], object_type="soft",
                    size=(0.11589, 0.11777, 0.04085), default_pos=(0.47, 0.0, 0.0202),
                    mesh_path=str(_OBJ_DIR / "pan.obj")),
})

# # pet: Objaverse-LVIS pet (unknown bucket, uid 5e3e6f8692584d67956cc501b869e02b), object-expansion batch
OBJECT_MAP.update({
    "pet": ObjectDef("pet", MATERIALS["objexp_pet"], object_type="soft",
                    size=(0.10400, 0.04362, 0.11516), default_pos=(0.47, 0.0, 0.0572),
                    mesh_path=str(_OBJ_DIR / "pet.obj")),
})

# # pillow: Objaverse-LVIS pillow (unknown bucket, uid 49ff5037af0b45fbab69680fcb3228a2), object-expansion batch
OBJECT_MAP.update({
    "pillow": ObjectDef("pillow", MATERIALS["objexp_pillow"], object_type="soft",
                    size=(0.04993, 0.04922, 0.04980), default_pos=(0.47, 0.0, 0.0256),
                    mesh_path=str(_OBJ_DIR / "pillow.obj")),
})

# # pocket_watch: Objaverse-LVIS pocket_watch (unknown bucket, uid 515b783e0444464c84d7fa0cebd31cab), object-expansion batch
OBJECT_MAP.update({
    "pocket_watch": ObjectDef("pocket_watch", MATERIALS["objexp_pocket_watch"], object_type="soft",
                    size=(0.05133, 0.04552, 0.06903), default_pos=(0.47, 0.0, 0.0290),
                    mesh_path=str(_OBJ_DIR / "pocket_watch.obj")),
})

# # postcard: Objaverse-LVIS postcard (unknown bucket, uid 104d34aa17e648adb50231219edf8665), object-expansion batch
OBJECT_MAP.update({
    "postcard": ObjectDef("postcard", MATERIALS["objexp_postcard"], object_type="soft",
                    size=(0.11287, 0.04643, 0.11261), default_pos=(0.47, 0.0, 0.0607),
                    mesh_path=str(_OBJ_DIR / "postcard.obj")),
})

# # pot: Objaverse-LVIS pot (unknown bucket, uid 6791a4ce3cb44c7c88b5713b5298d908), object-expansion batch
OBJECT_MAP.update({
    "pot": ObjectDef("pot", MATERIALS["objexp_pot"], object_type="soft",
                    size=(0.04735, 0.04730, 0.04769), default_pos=(0.47, 0.0, 0.0243),
                    mesh_path=str(_OBJ_DIR / "pot.obj")),
})

# # radio_receiver: Objaverse-LVIS radio_receiver (unknown bucket, uid 9033159bd5ad4737b75d6a81f0a8301b), object-expansion batch
OBJECT_MAP.update({
    "radio_receiver": ObjectDef("radio_receiver", MATERIALS["objexp_radio_receiver"], object_type="soft",
                    size=(0.10324, 0.04878, 0.06251), default_pos=(0.47, 0.0, 0.0314),
                    mesh_path=str(_OBJ_DIR / "radio_receiver.obj")),
})

# # saucepan: Objaverse-LVIS saucepan (unknown bucket, uid e2da46f23af54a7ca5bcaf7581dbfa6b), object-expansion batch
OBJECT_MAP.update({
    "saucepan": ObjectDef("saucepan", MATERIALS["objexp_saucepan"], object_type="soft",
                    size=(0.09957, 0.09960, 0.04842), default_pos=(0.47, 0.0, 0.0260),
                    mesh_path=str(_OBJ_DIR / "saucepan.obj")),
})

# # sharpener: Objaverse-LVIS sharpener (unknown bucket, uid 1d6c8a031c41489ebecda344fb2d4807), object-expansion batch
OBJECT_MAP.update({
    "sharpener": ObjectDef("sharpener", MATERIALS["objexp_sharpener"], object_type="soft",
                    size=(0.07308, 0.04370, 0.04958), default_pos=(0.47, 0.0, 0.0252),
                    mesh_path=str(_OBJ_DIR / "sharpener.obj")),
})

# # shower_cap: Objaverse-LVIS shower_cap (unknown bucket, uid 240af2279855434b8b1e2e5d04ae30c6), object-expansion batch
OBJECT_MAP.update({
    "shower_cap": ObjectDef("shower_cap", MATERIALS["objexp_shower_cap"], object_type="soft",
                    size=(0.04945, 0.04934, 0.04971), default_pos=(0.47, 0.0, 0.0253),
                    mesh_path=str(_OBJ_DIR / "shower_cap.obj")),
})

# # shredder: Objaverse-LVIS shredder_(for_paper) (unknown bucket, uid 3932389d516a4cbfb3644f40922e542d), object-expansion batch
OBJECT_MAP.update({
    "shredder": ObjectDef("shredder", MATERIALS["objexp_shredder"], object_type="soft",
                    size=(0.11105, 0.05173, 0.10947), default_pos=(0.47, 0.0, 0.0490),
                    mesh_path=str(_OBJ_DIR / "shredder.obj")),
})

# # skullcap: Objaverse-LVIS skullcap (unknown bucket, uid 276a01e4b8484fcda02061e073662dc7), object-expansion batch
OBJECT_MAP.update({
    "skullcap": ObjectDef("skullcap", MATERIALS["objexp_skullcap"], object_type="soft",
                    size=(0.04532, 0.04993, 0.06078), default_pos=(0.47, 0.0, 0.0304),
                    mesh_path=str(_OBJ_DIR / "skullcap.obj")),
})

# # smoothie: Objaverse-LVIS smoothie (unknown bucket, uid bd769a8792b9477a9de7b4cfb2d96c0e), object-expansion batch
OBJECT_MAP.update({
    "smoothie": ObjectDef("smoothie", MATERIALS["objexp_smoothie"], object_type="soft",
                    size=(0.03860, 0.03846, 0.04222), default_pos=(0.47, 0.0, 0.0278),
                    mesh_path=str(_OBJ_DIR / "smoothie.obj")),
})

# # squid: Objaverse-LVIS squid_(food) (unknown bucket, uid 0fb0c4ff0d3f489288caa0afef723230), object-expansion batch
OBJECT_MAP.update({
    "squid": ObjectDef("squid", MATERIALS["objexp_squid"], object_type="soft",
                    size=(0.04583, 0.04060, 0.07437), default_pos=(0.47, 0.0, 0.0404),
                    mesh_path=str(_OBJ_DIR / "squid.obj")),
})

# # strainer: Objaverse-LVIS strainer (unknown bucket, uid 39a813c157e94a3d9d1f2332134a47bb), object-expansion batch
OBJECT_MAP.update({
    "strainer": ObjectDef("strainer", MATERIALS["objexp_strainer"], object_type="soft",
                    size=(0.04400, 0.06838, 0.05032), default_pos=(0.47, 0.0, 0.0260),
                    mesh_path=str(_OBJ_DIR / "strainer.obj")),
})

# # sweet_potato: Objaverse-LVIS sweet_potato (unknown bucket, uid 4de96f97ca814709a7664b1831a7c9c9), object-expansion batch
OBJECT_MAP.update({
    "sweet_potato": ObjectDef("sweet_potato", MATERIALS["objexp_sweet_potato"], object_type="soft",
                    size=(0.05855, 0.04961, 0.04956), default_pos=(0.47, 0.0, 0.0258),
                    mesh_path=str(_OBJ_DIR / "sweet_potato.obj")),
})

# # tambourine: Objaverse-LVIS tambourine (unknown bucket, uid 3e6004858508416293b536efaa2cbedc), object-expansion batch
OBJECT_MAP.update({
    "tambourine": ObjectDef("tambourine", MATERIALS["objexp_tambourine"], object_type="soft",
                    size=(0.08154, 0.07276, 0.10952), default_pos=(0.47, 0.0, 0.0419),
                    mesh_path=str(_OBJ_DIR / "tambourine.obj")),
})

# # tartan: Objaverse-LVIS tartan (unknown bucket, uid 2211bfe7312348d795e1fce4f925dce6), object-expansion batch
OBJECT_MAP.update({
    "tartan": ObjectDef("tartan", MATERIALS["objexp_tartan"], object_type="soft",
                    size=(0.07786, 0.11150, 0.04681), default_pos=(0.47, 0.0, 0.0245),
                    mesh_path=str(_OBJ_DIR / "tartan.obj")),
})

# # telephoto_lens: Objaverse-LVIS telephoto_lens (unknown bucket, uid 09247d35f0e244c29c6b7f7c36a12d45), object-expansion batch
OBJECT_MAP.update({
    "telephoto_lens": ObjectDef("telephoto_lens", MATERIALS["objexp_telephoto_lens"], object_type="soft",
                    size=(0.04999, 0.04104, 0.05003), default_pos=(0.47, 0.0, 0.0255),
                    mesh_path=str(_OBJ_DIR / "telephoto_lens.obj")),
})

# # thimble: Objaverse-LVIS thimble (unknown bucket, uid 13cb5f6c327c4aeabe1f4690dbe73838), object-expansion batch
OBJECT_MAP.update({
    "thimble": ObjectDef("thimble", MATERIALS["objexp_thimble"], object_type="soft",
                    size=(0.04542, 0.05070, 0.06213), default_pos=(0.47, 0.0, 0.0320),
                    mesh_path=str(_OBJ_DIR / "thimble.obj")),
})

# # timer: Objaverse-LVIS timer (unknown bucket, uid 89cee4a742ef47df9769b8bc947e0d61), object-expansion batch
OBJECT_MAP.update({
    "timer": ObjectDef("timer", MATERIALS["objexp_timer"], object_type="soft",
                    size=(0.10823, 0.05089, 0.09410), default_pos=(0.47, 0.0, 0.0503),
                    mesh_path=str(_OBJ_DIR / "timer.obj")),
})

# # tote_bag: Objaverse-LVIS tote_bag (unknown bucket, uid 000a3d9fa4ff4c888e71e698694eb0b0), object-expansion batch
OBJECT_MAP.update({
    "tote_bag": ObjectDef("tote_bag", MATERIALS["objexp_tote_bag"], object_type="soft",
                    size=(0.13100, 0.03783, 0.14145), default_pos=(0.47, 0.0, 0.0698),
                    mesh_path=str(_OBJ_DIR / "tote_bag.obj")),
})

# # volleyball: Objaverse-LVIS volleyball (unknown bucket, uid 6554891b758246348b682dfff4e4b462), object-expansion batch
OBJECT_MAP.update({
    "volleyball": ObjectDef("volleyball", MATERIALS["objexp_volleyball"], object_type="soft",
                    size=(0.04485, 0.04485, 0.04485), default_pos=(0.47, 0.0, 0.0234),
                    mesh_path=str(_OBJ_DIR / "volleyball.obj")),
})

# # wallet: Objaverse-LVIS wallet (unknown bucket, uid b891198a35a64b2c9c3c1a26338b1a48), object-expansion batch
OBJECT_MAP.update({
    "wallet": ObjectDef("wallet", MATERIALS["objexp_wallet"], object_type="soft",
                    size=(0.11835, 0.10982, 0.07190), default_pos=(0.47, 0.0, 0.0376),
                    mesh_path=str(_OBJ_DIR / "wallet.obj")),
})

# # water_faucet: Objaverse-LVIS water_faucet (unknown bucket, uid 10367ce0fcbc45279f59648e80e26139), object-expansion batch
OBJECT_MAP.update({
    "water_faucet": ObjectDef("water_faucet", MATERIALS["objexp_water_faucet"], object_type="soft",
                    size=(0.04218, 0.07454, 0.11511), default_pos=(0.47, 0.0, 0.0520),
                    mesh_path=str(_OBJ_DIR / "water_faucet.obj")),
})

def get_object_def(name: str) -> ObjectDef:
    if name not in OBJECT_MAP:
        raise KeyError(f"Unknown object {name!r}; known objects: {sorted(OBJECT_MAP)}")
    return OBJECT_MAP[name]
