"""Object registry: name -> ObjectDef (geometry + default material).

OBJECT_MAP is the single source of truth for what each object name spawns. Objects
are either a primitive MPM/rigid box (mesh_path=None) or a scanned mesh (mesh_path
set -> Genesis loads gs.morphs.Mesh). Scanned meshes live in assets/objects/ and are
stored in METERS, so no scale conversion is needed at the call site.

SceneBuilder reads OBJECT_MAP to turn a SceneSpec ObjectEntry (which may override
E/nu/rho/scale/pose) into Genesis morph + material calls.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

from gentle_manip.assets.materials import MATERIALS, Material

_OBJ_DIR = Path(__file__).resolve().parent / "objects"


@dataclass(frozen=True)
class ObjectDef:
    name: str
    material: Material
    object_type: str = "soft"                       # "soft" (MPM) | "rigid"
    size: Tuple[float, float, float] = (0.04, 0.04, 0.04)   # primitive box extents (m)
    default_pos: Tuple[float, float, float] = (0.50, 0.0, 0.03)  # resting pose (m)
    mesh_path: Optional[str] = None                 # reserved; None => primitive box


# The validated baseline matches examples/gs_sim_backend_dev.py: a 4 cm tofu cube
# resting at (0.50, 0, 0.03), within reach and the MPM bounds.
OBJECT_MAP: dict[str, ObjectDef] = {
    # 3 cm tofu block (2026-08-25): the item-1 cube geometry as a SOFT object — the second
    # category for the generalist push. Subdivided cube mesh so shape DR / CMA-ES SDF work.
    "tofu":    ObjectDef("tofu", MATERIALS["tofu"], object_type="soft",
                         size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.0, 0.016),
                         mesh_path=str(_OBJ_DIR / "tofu.obj")),
    "gelatin": ObjectDef("gelatin", MATERIALS["gelatin"]),
    "sponge":  ObjectDef("sponge", MATERIALS["sponge"]),
    # 3 cm cube matching the real red cube the DP3 policy was trained on; rests on
    # the table (half-extent 0.015 -> center z ~0.015 after settling).
    "red_cube": ObjectDef("red_cube", MATERIALS["red_cube"],
                          size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.011, 0.02)),
    # Gripper-width calibration cubes (use as rigid): known sizes spread across x so
    # all four fit in one scene; spawn z = half-extent so they rest on the table.
    "cal_cube_6": ObjectDef("cal_cube_6", MATERIALS["red_cube"], size=(0.06, 0.06, 0.06), default_pos=(0.34, 0.0, 0.035)),
    "cal_cube_5": ObjectDef("cal_cube_5", MATERIALS["red_cube"], size=(0.05, 0.05, 0.05), default_pos=(0.42, 0.0, 0.030)),
    "cal_cube_4": ObjectDef("cal_cube_4", MATERIALS["red_cube"], size=(0.04, 0.04, 0.04), default_pos=(0.50, 0.0, 0.025)),
    "cal_cube_3": ObjectDef("cal_cube_3", MATERIALS["red_cube"], size=(0.03, 0.03, 0.03), default_pos=(0.58, 0.0, 0.020)),
    # Real scanned edible mushroom (assets/objects/mushroom.obj, in meters: ~3.3 x 3.2
    # x 3.5 cm). Soft MPM body; rests on the table (mesh bottom at z=-0.0148, so
    # default_pos z=0.016 puts it just above the surface). size is informational only
    # (ignored for meshes). Material is the soft-end "Config C" (see materials.py).
    "mushroom": ObjectDef("mushroom", MATERIALS["mushroom"], object_type="soft",
                          size=(0.033, 0.032, 0.035), default_pos=(0.47, 0.0, 0.016),
                          mesh_path=str(_OBJ_DIR / "mushroom.obj")),
    # TripoSG-scanned real-mushroom variants (MIT-licensed generator) (item 6): rotated to the same z-up/cap-up
    # convention and uniformly scaled to the nominal mushroom's mean extent (~33 mm); same
    # material/spawn conventions, so they drop into any mushroom task via object name.
    "mushroom1": ObjectDef("mushroom1", MATERIALS["mushroom"], object_type="soft",
                           size=(0.0323, 0.0322, 0.0351), default_pos=(0.47, 0.0, 0.016),
                           mesh_path=str(_OBJ_DIR / "mushroom1.obj")),
    "mushroom2": ObjectDef("mushroom2", MATERIALS["mushroom"], object_type="soft",
                           size=(0.0318, 0.0319, 0.0359), default_pos=(0.47, 0.0, 0.016),
                           mesh_path=str(_OBJ_DIR / "mushroom2.obj")),
    "mushroom3": ObjectDef("mushroom3", MATERIALS["mushroom"], object_type="soft",
                           size=(0.0357, 0.0326, 0.0313), default_pos=(0.47, 0.0, 0.016),
                           mesh_path=str(_OBJ_DIR / "mushroom3.obj")),

    # ── Grasp-benchmark shape set ────────────────────────────────────────────────────────────────
    # Three extra soft objects that bracket the geometry axis the mushroom alone cannot test.
    # Meshes are generated by assets/make_primitive_meshes.py, in METRES, xy-centred with the base
    # at z=0 — so default_pos.z is half-height + ~1 mm clearance (a soft body must SPAWN RESTING;
    # dropping it from height blows up MPM). NOTE object_type here is documentation only: the sim
    # reads `object_type` from the TASK config, not from this field.
    #
    # Cylinder r=2.5cm x h=4cm: smooth and curved with no antipodal faces, and the widest object in
    # the set (5 cm across, vs the gripper's ~7.9 cm usable opening).
    "cylinder": ObjectDef("cylinder", MATERIALS["soft_shape"], object_type="soft",
                          size=(0.05, 0.05, 0.04), default_pos=(0.47, 0.0, 0.021),
                          mesh_path=str(_OBJ_DIR / "cylinder.obj")),
    # Cube 4cm: flat antipodal faces and SHARP edges — the control case for a metric tuned on
    # organic blobs. Must be planned with prepare=False; the FEM path's watertight voxel remesh
    # rounds sharp edges, which would erase exactly what this object is here to test.
    # TRUE 3 cm sharp cube (item 1: the real 3 cm cube probe below the arm). RIGID — the real
    # counterpart is a solid cube; mesh (not Box) so the FEM grasp synthesis can plan on it.
    # spawn z = half-side + 1 mm clearance (centroid-origin mesh).
    "cube3": ObjectDef("cube3", MATERIALS["red_cube"], object_type="rigid",
                       size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.0, 0.016),
                       mesh_path=str(_OBJ_DIR / "cube3.obj")),
    # SOFT twin of cube3 (2026-09-03). ADDITIVE — cube3 stays rigid so every existing dataset and
    # policy is untouched. Same 3 cm mesh, MPM instead of rigid, soft_shape material (E=300 kPa,
    # the stiffest validated MPM preset — "Config C") because it stands in for a real SOLID cube:
    # a softer preset (red_cube, E=30 kPa) would visibly squash under the grasp and diverge from
    # the real object. Used for the 2026-09-03 D435i paired-replay + 200-demo campaign, where the
    # research question is gentleness, so the sim object must be deformable.
    "cube3_soft": ObjectDef("cube3_soft", MATERIALS["soft_shape"], object_type="soft",
                            size=(0.03, 0.03, 0.03), default_pos=(0.47, 0.0, 0.016),
                            mesh_path=str(_OBJ_DIR / "cube3.obj")),
    "cube4": ObjectDef("cube4", MATERIALS["soft_shape"], object_type="soft",
                       size=(0.04, 0.04, 0.04), default_pos=(0.47, 0.0, 0.021),
                       mesh_path=str(_OBJ_DIR / "cube4.obj")),
    # Raspberry ~1.5cm: the small, fragile, bumpy case. NOTE it spans only ~4 cells at the
    # mushroom task's MPM grid density (4 mm cells), so its task config must tighten mpm_bounds and
    # raise mpm_grid_density or the contact is unresolved — see docs/grasp_synthesis_v4_plan.md.
    "cherry_tomato": ObjectDef("cherry_tomato", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.0247, 0.025, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato2.obj")),
    "tomato": ObjectDef("tomato", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0459, 0.0599), default_pos=(0.47, 0.0, 0.0307),
                        mesh_path=str(_OBJ_DIR / "tomato1.obj")),
    "banana_chunk": ObjectDef("banana_chunk", MATERIALS["banana_chunk"], object_type="soft",
                        size=(0.0337, 0.035, 0.0204), default_pos=(0.47, 0.0, 0.011),
                        mesh_path=str(_OBJ_DIR / "banana_chunk.obj")),
    "pasta_bundle": ObjectDef("pasta_bundle", MATERIALS["pasta_bundle"], object_type="soft",
                        size=(0.06, 0.0249, 0.0249), default_pos=(0.47, 0.0, 0.0138),
                        mesh_path=str(_OBJ_DIR / "pasta_bundle.obj")),
    # Photo-derived fruit variants (TripoSG, cluster agent 2026-08-27). Kept = passed the
    # agent's usability gate (topology + photo-silhouette consistency) AND our
    # category-appropriateness check (volume within 0.5-2x the category median, aspect < 1.6,
    # euler 2). Each is uniformly scaled to the category's already-validated nominal extent.
    "cherry_tomato1": ObjectDef("cherry_tomato1", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.025, 0.0241, 0.0245), default_pos=(0.47, 0.0, 0.0132),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato1.obj")),
    "cherry_tomato2": ObjectDef("cherry_tomato2", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.0247, 0.025, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato2.obj")),
    "cherry_tomato3": ObjectDef("cherry_tomato3", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.025, 0.0167, 0.0194), default_pos=(0.47, 0.0, 0.0107),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato3.obj")),
    "cherry_tomato5": ObjectDef("cherry_tomato5", MATERIALS["cherry_tomato"], object_type="soft",
                        size=(0.0198, 0.025, 0.0198), default_pos=(0.47, 0.0, 0.0113),
                        mesh_path=str(_OBJ_DIR / "cherry_tomato5.obj")),
    "raspberry1": ObjectDef("raspberry1", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0154, 0.0153, 0.0154), default_pos=(0.47, 0.0, 0.0087),
                        mesh_path=str(_OBJ_DIR / "raspberry1.obj")),
    "raspberry2": ObjectDef("raspberry2", MATERIALS["raspberry"], object_type="soft",
                        size=(0.014, 0.0154, 0.0137), default_pos=(0.47, 0.0, 0.0079),
                        mesh_path=str(_OBJ_DIR / "raspberry2.obj")),
    "raspberry3": ObjectDef("raspberry3", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0154, 0.012, 0.0133), default_pos=(0.47, 0.0, 0.0078),
                        mesh_path=str(_OBJ_DIR / "raspberry3.obj")),
    "raspberry4": ObjectDef("raspberry4", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0154, 0.0117, 0.0113), default_pos=(0.47, 0.0, 0.0067),
                        mesh_path=str(_OBJ_DIR / "raspberry4.obj")),
    "raspberry5": ObjectDef("raspberry5", MATERIALS["raspberry"], object_type="soft",
                        size=(0.0146, 0.0154, 0.0149), default_pos=(0.47, 0.0, 0.0083),
                        mesh_path=str(_OBJ_DIR / "raspberry5.obj")),
    "tomato1": ObjectDef("tomato1", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0459, 0.0599), default_pos=(0.47, 0.0, 0.0307),
                        mesh_path=str(_OBJ_DIR / "tomato1.obj")),
    "tomato3": ObjectDef("tomato3", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0527, 0.0599), default_pos=(0.47, 0.0, 0.0308),
                        mesh_path=str(_OBJ_DIR / "tomato3.obj")),
    "tomato4": ObjectDef("tomato4", MATERIALS["tomato"], object_type="soft",
                        size=(0.0531, 0.06, 0.0516), default_pos=(0.47, 0.0, 0.0268),
                        mesh_path=str(_OBJ_DIR / "tomato4.obj")),
    "tomato5": ObjectDef("tomato5", MATERIALS["tomato"], object_type="soft",
                        size=(0.06, 0.0537, 0.059), default_pos=(0.47, 0.0, 0.0303),
                        mesh_path=str(_OBJ_DIR / "tomato5.obj")),
    # Primitive diversity objects (2026-08-30, user request) — ALL tofu material. Shape-class
    # probes for the FROZEN v4.1 synthesis: cylinder/sphere/lamp user-specified; cuboid/
    # ellipsoid/torus proposed (flat-face + smooth anisotropy + topology). v4.1 parameters are
    # NOT to be modified regardless of how these perform (paper freeze, deadline 2026-09-15).
    "prim_cylinder": ObjectDef("prim_cylinder", MATERIALS["tofu"], object_type="soft",
                        size=(0.04, 0.04, 0.05), default_pos=(0.47, 0.0, 0.026),
                        mesh_path=str(_OBJ_DIR / "prim_cylinder.obj")),
    "prim_sphere": ObjectDef("prim_sphere", MATERIALS["tofu"], object_type="soft",
                        size=(0.04, 0.04, 0.04), default_pos=(0.47, 0.0, 0.021),
                        mesh_path=str(_OBJ_DIR / "prim_sphere.obj")),
    "prim_lamp": ObjectDef("prim_lamp", MATERIALS["tofu"], object_type="soft",
                        size=(0.03, 0.03, 0.052), default_pos=(0.47, 0.0, 0.037),
                        mesh_path=str(_OBJ_DIR / "prim_lamp.obj")),
    "prim_cuboid": ObjectDef("prim_cuboid", MATERIALS["tofu"], object_type="soft",
                        size=(0.04, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_cuboid.obj")),
    "prim_ellipsoid": ObjectDef("prim_ellipsoid", MATERIALS["tofu"], object_type="soft",
                        size=(0.05, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_ellipsoid.obj")),
    "prim_torus": ObjectDef("prim_torus", MATERIALS["tofu"], object_type="soft",
                        size=(0.042, 0.042, 0.014), default_pos=(0.47, 0.0, 0.008),
                        mesh_path=str(_OBJ_DIR / "prim_torus.obj")),
    # *_mush VARIANTS (2026-08-31): the same six primitive meshes with MUSHROOM material,
    # ADDED as separate entries per user instruction (never override existing entries — the
    # tofu-material prim_* set above stays intact for the material A/B and to avoid merge
    # conflicts with the cluster). Force-budget prediction: curved shapes recover to ~75-90%.
    "prim_cylinder_mush": ObjectDef("prim_cylinder_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.04, 0.04, 0.05), default_pos=(0.47, 0.0, 0.026),
                        mesh_path=str(_OBJ_DIR / "prim_cylinder.obj")),
    "prim_sphere_mush": ObjectDef("prim_sphere_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.04, 0.04, 0.04), default_pos=(0.47, 0.0, 0.021),
                        mesh_path=str(_OBJ_DIR / "prim_sphere.obj")),
    "prim_lamp_mush": ObjectDef("prim_lamp_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.03, 0.03, 0.052), default_pos=(0.47, 0.0, 0.037),
                        mesh_path=str(_OBJ_DIR / "prim_lamp.obj")),
    "prim_cuboid_mush": ObjectDef("prim_cuboid_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.04, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_cuboid.obj")),
    "prim_ellipsoid_mush": ObjectDef("prim_ellipsoid_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.05, 0.03, 0.025), default_pos=(0.47, 0.0, 0.0135),
                        mesh_path=str(_OBJ_DIR / "prim_ellipsoid.obj")),
    "prim_torus_mush": ObjectDef("prim_torus_mush", MATERIALS["mushroom"], object_type="soft",
                        size=(0.042, 0.042, 0.014), default_pos=(0.47, 0.0, 0.008),
                        mesh_path=str(_OBJ_DIR / "prim_torus.obj")),
    "raspberry": ObjectDef("raspberry", MATERIALS["raspberry"], object_type="soft",
                        size=(0.014, 0.0154, 0.0137), default_pos=(0.47, 0.0, 0.0079),
                        mesh_path=str(_OBJ_DIR / "raspberry2.obj")),
    # Banana ~9.5 cm (photo-reconstructed, stem + its flat cut face removed; user-set nominal
    # extent). The mesh is a strong crescent, so the bbox is nearly square in plane
    # (9.5 x 9.2 cm) and 3.24 cm thick — the thickness is what the gripper closes on. At this
    # size it is ~70 g, needing only ~0.5 N of grip; the earlier 17 cm cut was 398 g (~2.8 N)
    # and its 20 cm CMA search box made the planner miss the thin feasible band entirely.
    "banana": ObjectDef("banana", MATERIALS["banana"], object_type="soft",
                        size=(0.0707, 0.095, 0.0186), default_pos=(0.47, 0.0, 0.0104),
                        mesh_path=str(_OBJ_DIR / "banana.obj")),
    # Strawberry ~4 cm (photo-reconstructed, calyx/leaves removed and the body made watertight
    # by a voxel remesh with morphological opening). Squat: 4.0 x 3.8 x 3.25 cm (tip->crown is
    # the SHORT axis, z), so an exact "4 cm long x 3 cm wide" is not reachable without
    # distorting it — uniformly scaled to a 4 cm longest extent instead.
    "strawberry": ObjectDef("strawberry", MATERIALS["strawberry"], object_type="soft",
                            size=(0.040, 0.038, 0.0325), default_pos=(0.47, 0.0, 0.0204),
                            mesh_path=str(_OBJ_DIR / "strawberry.obj")),
}


# ── Extruded letters A-Z (2026-09-05): ~50 mm tall, ~6 mm thick, lying FLAT (thin axis = z), tofu
# material — complex-geometry test objects. Meshes are metres, centroid at the origin. Additive.
OBJECT_MAP.update({
    "letter_a": ObjectDef("letter_a", MATERIALS["tofu"], object_type="soft",
                        size=(0.0486, 0.0500, 0.0058), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_a.obj")),
    "letter_b": ObjectDef("letter_b", MATERIALS["tofu"], object_type="soft",
                        size=(0.0343, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_b.obj")),
    "letter_c": ObjectDef("letter_c", MATERIALS["tofu"], object_type="soft",
                        size=(0.0439, 0.0500, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_c.obj")),
    "letter_d": ObjectDef("letter_d", MATERIALS["tofu"], object_type="soft",
                        size=(0.0460, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_d.obj")),
    "letter_e": ObjectDef("letter_e", MATERIALS["tofu"], object_type="soft",
                        size=(0.0290, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_e.obj")),
    "letter_f": ObjectDef("letter_f", MATERIALS["tofu"], object_type="soft",
                        size=(0.0267, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_f.obj")),
    "letter_g": ObjectDef("letter_g", MATERIALS["tofu"], object_type="soft",
                        size=(0.0445, 0.0500, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_g.obj")),
    "letter_h": ObjectDef("letter_h", MATERIALS["tofu"], object_type="soft",
                        size=(0.0424, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_h.obj")),
    "letter_i": ObjectDef("letter_i", MATERIALS["tofu"], object_type="soft",
                        size=(0.0072, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_i.obj")),
    "letter_j": ObjectDef("letter_j", MATERIALS["tofu"], object_type="soft",
                        size=(0.0129, 0.0500, 0.0044), default_pos=(0.47, 0.0, 0.0032),
                        mesh_path=str(_OBJ_DIR / "letter_j.obj")),
    "letter_k": ObjectDef("letter_k", MATERIALS["tofu"], object_type="soft",
                        size=(0.0425, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_k.obj")),
    "letter_l": ObjectDef("letter_l", MATERIALS["tofu"], object_type="soft",
                        size=(0.0298, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_l.obj")),
    "letter_m": ObjectDef("letter_m", MATERIALS["tofu"], object_type="soft",
                        size=(0.0466, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_m.obj")),
    "letter_n": ObjectDef("letter_n", MATERIALS["tofu"], object_type="soft",
                        size=(0.0463, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_n.obj")),
    "letter_o": ObjectDef("letter_o", MATERIALS["tofu"], object_type="soft",
                        size=(0.0500, 0.0477, 0.0055), default_pos=(0.47, 0.0, 0.0037),
                        mesh_path=str(_OBJ_DIR / "letter_o.obj")),
    "letter_p": ObjectDef("letter_p", MATERIALS["tofu"], object_type="soft",
                        size=(0.0315, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_p.obj")),
    "letter_q": ObjectDef("letter_q", MATERIALS["tofu"], object_type="soft",
                        size=(0.0443, 0.0500, 0.0048), default_pos=(0.47, 0.0, 0.0034),
                        mesh_path=str(_OBJ_DIR / "letter_q.obj")),
    "letter_r": ObjectDef("letter_r", MATERIALS["tofu"], object_type="soft",
                        size=(0.0386, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_r.obj")),
    "letter_s": ObjectDef("letter_s", MATERIALS["tofu"], object_type="soft",
                        size=(0.0276, 0.0500, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_s.obj")),
    "letter_t": ObjectDef("letter_t", MATERIALS["tofu"], object_type="soft",
                        size=(0.0418, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_t.obj")),
    "letter_u": ObjectDef("letter_u", MATERIALS["tofu"], object_type="soft",
                        size=(0.0425, 0.0500, 0.0058), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_u.obj")),
    "letter_v": ObjectDef("letter_v", MATERIALS["tofu"], object_type="soft",
                        size=(0.0439, 0.0500, 0.0058), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_v.obj")),
    "letter_w": ObjectDef("letter_w", MATERIALS["tofu"], object_type="soft",
                        size=(0.0500, 0.0330, 0.0038), default_pos=(0.47, 0.0, 0.0029),
                        mesh_path=str(_OBJ_DIR / "letter_w.obj")),
    "letter_x": ObjectDef("letter_x", MATERIALS["tofu"], object_type="soft",
                        size=(0.0500, 0.0484, 0.0057), default_pos=(0.47, 0.0, 0.0039),
                        mesh_path=str(_OBJ_DIR / "letter_x.obj")),
    "letter_y": ObjectDef("letter_y", MATERIALS["tofu"], object_type="soft",
                        size=(0.0443, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_y.obj")),
    "letter_z": ObjectDef("letter_z", MATERIALS["tofu"], object_type="soft",
                        size=(0.0451, 0.0500, 0.0059), default_pos=(0.47, 0.0, 0.0040),
                        mesh_path=str(_OBJ_DIR / "letter_z.obj")),
})

def get_object_def(name: str) -> ObjectDef:
    if name not in OBJECT_MAP:
        raise KeyError(f"Unknown object {name!r}; known objects: {sorted(OBJECT_MAP)}")
    return OBJECT_MAP[name]
